# Generated by Django 3.2.6 on 2021-08-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
